"use client";
import { useState } from "react";
import { ArrowDown, ArrowRight, Filter, RefreshCw, Sparkles, Users, X } from "lucide-react";

const weights: [string,number,string][]=[["Copy link",20,"You pass a post along outside X."],["Reply",5,"You join the conversation."],["Mutual reply",20,"You and the author follow each other."],["DM share",5,"You send it directly to someone."],["Quote",5,"You add your own words to a post."],["Follow author",4,"You choose to see more from them."],["Share",2,"You share it with your followers."],["Repost",1,"You put it back in your followers’ feeds."],["Like",.5,"A small positive signal."],["Post click",.4,"You open the conversation."],["Open link",.2,"You follow a link in the post."],["Photo / video",.05,"You expand or open media."],["Quoted click",.05,"You open a quoted post."],["Dwell time",.004,"Each second you spend reading."],["Unexplored (in-network)",.02,"A post you have not seen yet."],["Profile click",0,"No added score."],["Plain dwell",0,"No added score."],["Not dwelled",-.02,"You skip without dwelling."],["Block author",-31.2,"You block the author."],["Not interested",-43.2,"You ask for less like this."],["Mute author",-58.8,"You mute the author."],["Report",-234,"You report the post."]];
function Eyebrow({children}:{children:string}){return <span className="eyebrow mono"><i/>{children}</span>}
function Act({id,children,dark=false}:{id:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`section ${dark?"dark":"light"}`}><div className="wrap">{children}</div></section>}
function App(){
 const [pile,setPile]=useState("in"); const [selected,setSelected]=useState(0); const [follow,setFollow]=useState(false); const [hurt,setHurt]=useState(false);
 return <main>
  <div className="fixed top-0 left-0 right-0 z-50 h-1 bg-transparent"><div className="h-full bg-[#8f93c2]" style={{width:"18%"}}/></div>
  <Act id="top" dark><div className="hero relative flex min-h-[840px] flex-col justify-center overflow-hidden"><div className="code-texture">score = sum(weight * probability)
candidate.author = follow_graph
visibility = ALLOW | DROP
fresh_request()
engagement_history[]
ranking != visibility
feed_blender()</div><div className="relative z-10 max-w-4xl"><Eyebrow>Field guide / 01</Eyebrow><h1 className="serif mt-8 text-[82px] leading-[.94] tracking-[-.055em]">How the X algorithm<br/><em className="text-[#8f93c2]">actually works.</em></h1><p className="mt-8 max-w-xl text-xl leading-relaxed text-[#999ba6]">The For You feed, explained for the person scrolling it — not the engineer who built it.</p><p className="mono mt-14 text-[#999ba6]">Based on the code X publishes</p></div><div className="absolute bottom-10 left-0 right-0 flex items-center justify-between border-t border-white/20 pt-5 text-[#999ba6]"><span className="mono">Scroll to assemble your feed</span><ArrowDown size={18}/></div></div></Act>
  <Act id="refresh" dark><div className="grid items-center gap-12 bg-transparent md:grid-cols-[1fr_1fr]"><div><Eyebrow>Act 01 / Start fresh</Eyebrow><h2 className="serif">Your feed is built the moment you pull to refresh.</h2><p className="lede">Nothing is pre-baked. Every refresh is a fresh assembly, using who you are right now: your recent engagements, follows, blocks, mutes, and what you have already seen.</p></div><div className="sticky  dark-panel sticky rounded border border-white/20 p-8"><RefreshCw className="mb-8 text-[#8f93c2]"/><div className="space-y-3 font-mono text-sm text-[#999ba6]"><div className="flex justify-between"><span>your signals</span><span className="text-white">now</span></div><div className="h-px bg-white/20"/><div className="flex justify-between"><span>new assembly</span><span className="text-[#8f93c2]">fresh</span></div><div className="h-2 overflow-hidden rounded bg-white/10"><div className="h-full w-3/4 bg-[#8f93c2]"/></div></div></div></div></Act>
  <Act id="piles"><div className="grid items-start gap-12 bg-transparent md:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Act 02 / Candidates</Eyebrow><h2 className="serif">Two piles of posts.</h2><p className="lede">The feed gathers from people you follow and people you do not. Both piles arrive in parallel, then enter the same process.</p><div className="pill-toggle mt-8" role="group" aria-label="Choose a post pile"><button aria-pressed={pile==="in"} onClick={()=>setPile("in")}>In-network</button><button aria-pressed={pile==="out"} onClick={()=>setPile("out")}>Out-of-network</button></div></div><div className="sticky"><div className="post-card"><div className="mb-7 flex items-center gap-3"><div className="node"><Users size={20}/></div><div><p className="mono m-0">Showing the {pile === "in" ? "in-network" : "out-of-network"} pile</p><p className="mt-1 text-sm text-[#54565f]">{pile==="in"?"Recent posts from accounts you follow.":"Posts found by a retrieval model and by clustering who engages with what."}</p></div></div><div className="space-y-3">{(pile==="in"?["@people-you-follow","recent conversations","familiar voices"]:["@people-you-don’t-follow","retrieved interests","new voices"]).map((x,i)=><div key={x} className="flex items-center gap-3 rounded bg-[#e2dfd6] p-4"><span className="h-2 w-2 rounded-full bg-[#5a5e8e]"/><span>{x}</span><span className="mono ml-auto text-[#8c8054]">candidate 0{i+1}</span></div>)}</div></div></div></div></Act>
  <Act id="filters"><Eyebrow>Act 03 / Triage</Eyebrow><h2 className="serif max-w-3xl">Most posts are thrown out before they are ever scored.</h2><p className="lede mb-12">Before a score exists, filters remove posts that cannot belong in your feed.</p><div className="grid">{[["48h","Older than 48 hours"],["seen","Already shown this session"],["words","Muted keywords"],["blocks","Blocked or muted accounts"],["you","Your own posts"],["duplicates","Duplicates across sources"]].map(([a,b])=><div key={a}><div className="mb-8 flex justify-between"><Filter size={24} className="text-[#5a5e8e]"/><X size={18} className="text-[#a45c60]"/></div><p className="mono">{a}</p><p className="mt-2 text-lg">{b}</p></div>)}</div></Act>
  <Act id="model" dark><div className="grid items-center gap-12 bg-transparent md:grid-cols-2"><div><Eyebrow>Act 04 / Prediction</Eyebrow><h2 className="serif">One model guesses what you will do next.</h2><p className="lede">It reads your recent engagement history: the actions you took, in sequence. Each post gets its own score. Its neighbours do not change it.</p></div><div className="sticky  dark-panel sticky rounded border border-white/20 p-7"><div className="mb-6 flex items-center gap-3"><Sparkles className="text-[#8f93c2]"/><span className="mono">one post, many possibilities</span></div>{["like","reply","share","follow","keep reading"].map((x,i)=><div key={x} className="mb-4"><div className="mb-2 flex justify-between text-sm"><span>{x}</span><span className="text-[#999ba6]">{[42,18,12,7,65][i]}%</span></div><div className="h-2 rounded bg-white/10"><div className="h-full rounded bg-[#8f93c2]" style={{width:`${[42,18,12,7,65][i]}%`}}/></div></div>)}</div></div></Act>
  <Act id="weights"><Eyebrow>Act 05 / The score</Eyebrow><h2 className="serif max-w-3xl">Every action has a price.</h2><p className="lede">The model’s probabilities are combined with fixed weights. Positive actions lift a post. Negative actions pull it down.</p><div className="mt-10 grid gap-8 bg-transparent md:grid-cols-[1fr_1.4fr]"><div><div className="grid grid-cols-3 gap-2"><div className="rounded bg-[#efede6] p-4"><p className="mono">40×</p><p className="mt-2 text-sm">A copy-link share is worth 40 likes.</p></div><div className="rounded bg-[#efede6] p-4"><p className="mono">40×</p><p className="mt-2 text-sm">A mutual reply is worth 40 likes.</p></div><div className="rounded bg-[#efede6] p-4"><p className="mono">−468</p><p className="mt-2 text-sm">One report cancels 468 likes.</p></div></div><div className="mt-6 rounded border border-[#a9a492] bg-[#efede6] p-5"><div className="flex justify-between"><span className="mono">Selected action</span><span className="font-semibold">{weights[selected][0]}</span></div><p className="mt-5 text-xl">{weights[selected][2]}</p><p className="mono mt-4 text-[#5f8b6e]">weight {weights[selected][1]}</p></div></div><div className="rounded bg-[#282b35] p-5 text-[#f3f3f6]"><div className="mb-3 flex items-center justify-between"><span className="mono text-[#999ba6]">full weight table</span><div className="pill-toggle border-white/20"><button aria-pressed={!hurt} onClick={()=>setHurt(false)}>What helps</button><button aria-pressed={hurt} onClick={()=>setHurt(true)}>What hurts</button></div></div><div>{weights.filter(w=>hurt?w[1]<=0:w[1]>0).map((w,i)=>{const index=weights.indexOf(w);return <div key={w[0]} className={`weight-row ${selected===index?"active":""}`}><button onClick={()=>setSelected(index)} aria-label={`Explain ${w[0]}`}>{w[0]}</button><div className="flex items-center"><div className={`weight-bar ${Number(w[1])<0?"negative":""}`} style={{width:`${Math.min(Math.abs(Number(w[1]))/234*100,100)}%`}}/></div><span className="mono text-right">{w[1]}</span></div>})}</div></div></div></Act>
  <Act id="adjust" dark><Eyebrow>Act 06 / Balance</Eyebrow><h2 className="serif">Then three thumbs go on the scale.</h2><p className="lede">The raw score is adjusted so the feed has room for variety, new voices, and posts from outside your network.</p><div className="mt-12 grid">{[["Author diversity","Each next post from one author is cut in half, down to a 0.25 floor.","1 → 0.5 → 0.25"],["Out-of-network","A post from someone you do not follow gets a 0.75 multiplier. Topic-based discovery gets 0.5.","× 0.75"],["Cold start","Posts under 24 hours old from small authors are lifted toward positions 15–16.","↑ 15–16"]].map(([a,b,c])=><div key={a} className="border border-white/20 bg-[#282b35] p-6"><div className="mb-8 flex h-16 items-end gap-2">{[.9,.5,.25].map((h,i)=><div key={i} className="w-8 bg-[#8f93c2]" style={{height:`${h*100}%`}}/>)}</div><p className="mono text-[#8f93c2]">{c}</p><h3 className="serif mt-3 text-2xl">{a}</h3><p className="mt-3 text-[#999ba6]">{b}</p></div>)}</div></Act>
  <Act id="visibility"><div className="grid items-start gap-12 bg-transparent md:grid-cols-[1fr_1fr]"><div><Eyebrow>Act 07 / Visibility</Eyebrow><h2 className="serif">Being ranked first does not mean you will be shown.</h2><p className="lede">Ranking decides order. Visibility filtering decides whether a post can appear at all.</p><label className="mt-8 flex cursor-pointer items-center gap-3"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)} className="h-5 w-5 accent-[#5a5e8e]"/><span>Do you follow this account?</span></label></div><div className="sticky"><div className="post-card"><div className="mb-5 flex items-center justify-between"><span className="mono">same post / same rank</span><span className={`rounded px-3 py-2 text-sm font-semibold ${follow?"bg-[#5f8b6e] text-white":"bg-[#a45c60] text-white"}`}>{follow?"ALLOW":"DROP"}</span></div><h3 className="serif text-2xl">A post flagged as spam.</h3><p className="mt-3 text-[#54565f]">{follow?"You follow the author, so this post can still be shown.":"You do not follow the author, so a high-recall spam rule drops this recommendation."}</p><div className="mt-7 flex gap-3 text-sm"><span className="rounded bg-[#e2dfd6] px-3 py-2">ranked #1</span><ArrowRight className="mt-2" size={16}/><span className="rounded bg-[#e2dfd6] px-3 py-2">{follow?"shown":"removed"}</span></div></div></div></div></Act>
  <Act id="blend"><Eyebrow>Act 08 / Blend</Eyebrow><h2 className="serif max-w-3xl">Your feed is not only posts.</h2><p className="lede mb-12">The ranked slate is one source among several. Ads, Who to Follow, and prompts are interleaved around it.</p><div className="mx-auto max-w-2xl space-y-2">{["A post you follow","A post from discovery","Who to Follow","A post you follow","Prompt","Ad"].map((x,i)=><div key={i} className={`flex items-center gap-4 rounded border border-[#a9a492] p-4 ${x==="Ad"?"bg-[#d5d1c5]":""}`}><span className="mono text-[#5a5e8e]">{String(i+1).padStart(2,"0")}</span><span>{x}</span>{x!=="A post you follow"&&<span className="mono ml-auto text-[#8c8054]">interleaved</span>}</div>)}</div></Act>
  <Act id="takeaways" dark><Eyebrow>Act 09 / Takeaways</Eyebrow><h2 className="serif max-w-3xl">So, what actually matters?</h2><div className="mt-12 grid">{["Replies — especially between mutuals — and copy-link shares are powerful signals.","Likes are cheap. Reports, mutes, and “not interested” are enormous.","Posts have about 48 hours to live.","Repeating the same account decays fast.","New and small accounts get a real coded-in boost.","Muting, blocking, and not-interested reshape your own feed fastest.","If reach feels off, check Under the Hood for labels on your account."].map((x,i)=><div key={i} className="border border-white/20 p-6"><span className="mono text-[#8f93c2]">0{i+1}</span><p className="mt-5 text-lg text-[#f3f3f6]">{x}</p></div>)}</div></Act>
  <footer className="dark border-t border-white/20 py-14"><div className="wrap grid gap-8 md:grid-cols-2"><div><Eyebrow>Sources / Keep looking</Eyebrow><p className="mt-5 max-w-md text-[#999ba6]">Defaults published in the public x-algorithm repo, plus its README and DeepWiki. Production can differ: values come from configuration and experiments run on slices of traffic.</p></div><div className="md:text-right"><p className="mono text-[#999ba6]">Under the Hood</p><a className="mt-3 inline-block text-[#8f93c2] underline" href="https://x.com/i/under_the_hood">See visibility labels on your account <ArrowRight className="inline" size={15}/></a><p className="mono mt-12 text-[#999ba6]">Not affiliated with X</p></div></div></footer>
 </main>
}
export default App;
